export const Users = [
  {
    id:1,
    profilePicture: "post/person/1.jpg",
    username: "John Joana",
  },
  {
    id:2,
    profilePicture: "post/person/2.jpg",
    username: "Delwin Jnr",
  },
  {
    id:3,
    profilePicture: "post/person/3.jpg",
    username: "Monalisa Edem",
  },
  {
    id:4,
    profilePicture: "post/person/4.jpg",
    username: "Sir Martin",
  },
  {
    id:5,
    profilePicture: "post/person/5.jpg",
    username: "Solace Skylar",
  },
  {
    id:6,
    profilePicture: "post/person/6.jpg",
    username: "Edna Owusu",
  },
  {
    id:7,
    profilePicture: "post/person/7.jpg",
    username: "Efo Buju",
  },
  {
    id:8,
    profilePicture: "post/person/8.jpg",
    username: "Sir Code",
  },
  {
    id:9,
    profilePicture: "post/person/9.jpg",
    username: "Kwame Anti",
  },
  {
    id:10,
    profilePicture: "post/person/10.jpeg",
    username: "Mark Azumah",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "pokuase interchange located in Accra,Ghana.",
    photo: "post/post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "post/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "post/post/11.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "post/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "post/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "post/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "post/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "post/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Waakye, a Ghanaian meal.",
    photo: "post/post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "post/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
